// CHQ: Code generated by Gemini AI

// pages/api/graphql.ts (Example using Apollo Server Micro)

import { ApolloServer } from "apollo-server-micro";
import { typeDefs } from "../../graphql/schema"; // Your schema definition
import { resolvers } from "../../graphql/resolvers"; // Your resolvers

// 1. Initialize the Apollo Server with your schema and resolvers
const server = new ApolloServer({ typeDefs, resolvers });

// 2. Start the server (this is boilerplate for Apollo Server Micro)
const startServer = server.start();

export default async function handler(req, res) {
  // Required boilerplate to handle API routes in Next.js
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader(
    "Access-Control-Allow-Origin",
    "https://studio.apollographql.com"
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );

  if (req.method === "OPTIONS") {
    res.end();
    return;
  }

  // 3. Process the incoming GraphQL request
  await startServer;
  await server.createHandler({ path: "/api/graphql" })(req, res);
}

// Optional: Disable Next.js body parser to let Apollo Server handle it
export const config = {
  api: {
    bodyParser: false,
  },
};
